name: Auto-Close Issues on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  close-linked-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Close Issues
        uses: peter-evans/close-issues@v2
        with:
          issue-number: ${{ github.event.pull_request.body }}
          comment: "✅ This issue has been closed automatically as the related PR has been merged."
