name: Update Roadmap Progress

on:
  issues:
    types: [closed]

jobs:
  update-roadmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README Progress
        run: |
          sed -i "s/- \[ \] #${{ github.event.issue.number }}/- [x] #${{ github.event.issue.number }}/g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Marked issue #${{ github.event.issue.number }} as completed"
          git push
